import io
from typing import Optional
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import docx


class ExportService:
    @staticmethod
    def generate_pdf(title: str, content: str, doc_name: str = "AI Document Analysis") -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=20,
            leading=24,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=12
        )
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#64748B'),
            spaceAfter=20
        )
        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontSize=10.5,
            leading=16,
            textColor=colors.HexColor('#334155'),
            spaceAfter=10
        )
        
        story = [
            Paragraph(f"<b>{title}</b>", title_style),
            Paragraph(f"Source Document: {doc_name} &bull; Generated by AI Document Intelligence Assistant", subtitle_style),
            Spacer(1, 10)
        ]
        
        # Clean lines and paragraphs
        paragraphs = content.split("\n\n")
        for p in paragraphs:
            clean_p = p.replace("\n", " ").strip()
            if clean_p:
                # Basic markdown bold rendering
                clean_p = clean_p.replace("**", "<b>", 1)
                clean_p = clean_p.replace("**", "</b>", 1)
                story.append(Paragraph(clean_p, body_style))
                story.append(Spacer(1, 6))

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def generate_docx(title: str, content: str, doc_name: str = "AI Document Analysis") -> bytes:
        doc = docx.Document()
        doc.add_heading(title, level=0)
        doc.add_paragraph(f"Source Document: {doc_name} | AI Document Intelligence & Learning Assistant")
        doc.add_paragraph()
        
        paragraphs = content.split("\n\n")
        for p in paragraphs:
            clean_p = p.strip()
            if clean_p:
                doc.add_paragraph(clean_p)
                
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def generate_markdown(title: str, content: str, doc_name: str = "AI Document Analysis") -> str:
        return f"# {title}\n\n*Source Document: {doc_name}*\n*Generated by AI Document Intelligence & Learning Assistant*\n\n---\n\n{content}\n"

    @staticmethod
    def generate_txt(title: str, content: str, doc_name: str = "AI Document Analysis") -> str:
        return f"{title.upper()}\nSource Document: {doc_name}\n{'=' * 60}\n\n{content}\n"
